name: Backup Cloud Functions to GCS

on:
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: List Cloud Functions
        id: list_functions
        run: |
          mkdir -p backup/functions
          gcloud functions list --format="value(name)" > backup/functions/list.txt

      - name: Backup Functions to GCS
        run: |
          BUCKET_NAME="backup-gclient"
          DATE=$(date +%Y-%m-%d_%H-%M-%S)
          while read func_name; do
            echo "Exportando $func_name..."
            mkdir -p backup/functions/$func_name
            # Configuração YAML
            gcloud functions describe $func_name --format yaml > backup/functions/$func_name/config.yaml
            # Código
            gcloud functions download $func_name --destination backup/functions/$func_name/code
            # Upload para bucket
            gsutil -m cp -r backup/functions/$func_name gs://$BUCKET_NAME/$DATE/
          done < backup/functions/list.txt
