name: Auth Backup

on:
  schedule:
    - cron: "10 6 1 * *"
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install firebase-admin @google-cloud/storage

      - name: Run Auth Backup
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        run: node ./src/auth-backup.js
