name: Firestore Backup

on:
  schedule:
    - cron: "30 13 * * *"

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Firestore export
        run: |
          gcloud firestore export gs://backup-crm-gcvendas/firestore-$(date +%F)
